name: Publish a new development release

on:
  # Build releases on pushes to master and development branches
  # push:
  #   branches:
  #     - master
  #     - development
  # workflow_dispatch - manual trigger
  workflow_dispatch:
  schedule:
    # 23:30 CERN time
    - cron: "30 22 * * *"

jobs:
  # Check if new there were new commits in last 24 hours and save as "new_commits" variable
  check_for_commits:
    name: Check for new commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development

      - name: Print latest hash
        run: echo ${{ github.sha }}

      - name: Check if there are commit in past 24 hours
        id: newest_commit_check
        continue-on-error: true
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=new_commits::false"

    outputs:
      new_commits: ${{ steps.newest_commit_check.outputs.new_commits }}

  # Create a github release
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: [check_for_commits]
    if: ${{ needs.check_for_commits.outputs.new_commits != 'false' }}
    steps:
    - name: Create tag
      id: create_tag
      run: |
        branch_name=${GITHUB_REF##*/}
        release_timestamp=$(date +%Y-%m-%d_%H-%M-%S)
        tag=$branch_name-$release_timestamp
        echo "::set-output name=branch_name::$branch_name"
        echo "::set-output name=release_timestamp::$release_timestamp"
        echo "::set-output name=tag::$tag"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: true
        prerelease: false

    - name: Create artifact files
      run: |
        mkdir info
        echo "${{ steps.create_release.outputs.id }}" > info/release_id
        echo "${{ steps.create_release.outputs.upload_url }}" > info/upload_url
        echo "${{ steps.create_tag.outputs.tag }}.tar.gz" > info/archive_name
        echo "${{ steps.create_tag.outputs.release_timestamp }}" > info/release_timestamp
        echo "${{ steps.create_tag.outputs.branch_name }}" > info/branch_name

    - uses: actions/upload-artifact@v1
      with:
        name: info
        path: info

  build:
    name: Build release
    needs: [check_for_commits, release]
    if: ${{ needs.check_for_commits.outputs.new_commits != 'false' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: info

    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/checkout@v2
      with:
        ref: development
        path: ReReco

    - name: Checkout PdmVWebCore
      run: |
        cd ReReco
        git submodule init
        git submodule update

    - name: Save timestamp in release
      run: cp info/release_timestamp ReReco

    - name: Build Vue.js frontend and remove everything else from frontend
      run: |
        cd ReReco
        cd vue_frontend
        npm ci
        npm run build
        mv dist ..
        rm -rf *
        mv ../dist .

    - name: Create archive
      id: create_archive
      run: |
        archive_name=$(cat info/archive_name)
        tar -czf $archive_name ReReco/

    - name: Get upload info from artifact files
      id: upload_info
      run: |
        upload_url=$(cat info/upload_url)
        archive_name=$(cat info/archive_name)
        echo "::set-output name=upload_url::$upload_url"
        echo "::set-output name=archive_name::$archive_name"

    - name: Upload archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.upload_info.outputs.upload_url }}
        asset_path: ${{ steps.upload_info.outputs.archive_name }}
        asset_name: ${{ steps.upload_info.outputs.archive_name }}
        asset_content_type: application/gzip

  metadata:
    name: Publish release
    needs: [check_for_commits, build]
    if: ${{ needs.check_for_commits.outputs.new_commits != 'false' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: info

    - name: Set publish_info
      id: publish_info
      run: |
        release_id=$(cat info/release_id)
        branch_name=$(cat info/branch_name)
        echo "::set-output name=release_id::$release_id"
        echo "::set-output name=branch_name::$branch_name"

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.publish_info.outputs.release_id }}

    - name: Delete old releases and tags
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        delete_tag_pattern: ${{ steps.publish_info.outputs.branch_name }}-
        delete_tags: true
        keep_latest: 2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
